import jsPDF from 'jspdf'
import 'jspdf-autotable'
import * as XLSX from 'xlsx'

/**
 * Export portfolio data to PDF
 * @param {Object} portfolioSummary - Portfolio summary data
 * @param {Array} holdings - Array of holding objects
 * @param {string} fileName - Output file name
 */
export function exportPortfolioToPDF(portfolioSummary, holdings, fileName = 'portfolio-report.pdf') {
  const doc = new jsPDF()
  
  // Title
  doc.setFontSize(20)
  doc.text('Mutual Fund Portfolio Report', 14, 20)
  
  // Date
  doc.setFontSize(10)
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30)
  
  // Summary Section
  doc.setFontSize(14)
  doc.text('Portfolio Summary', 14, 45)
  
  doc.setFontSize(10)
  const summaryData = [
    ['Total Invested', `₹${portfolioSummary.totalInvested.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`],
    ['Current Value', `₹${portfolioSummary.currentValue.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`],
    ['Total Return', `₹${portfolioSummary.totalReturn.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`],
    ['Return %', `${portfolioSummary.returnPercentage.toFixed(2)}%`],
    ['Holdings Count', portfolioSummary.holdingsCount.toString()]
  ]
  
  doc.autoTable({
    startY: 50,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [30, 58, 138] }
  })
  
  // Holdings Section
  doc.setFontSize(14)
  doc.text('Holdings Details', 14, doc.lastAutoTable.finalY + 15)
  
  const holdingsData = holdings.map(h => [
    h.code,
    h.name,
    h.units.toFixed(3),
    `₹${h.avgNav.toFixed(2)}`,
    `₹${(h.units * h.avgNav).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`,
    h.currentNav ? `₹${h.currentNav.toFixed(2)}` : 'N/A',
    h.currentNav ? `₹${(h.units * h.currentNav).toLocaleString('en-IN', { maximumFractionDigits: 2 })}` : 'N/A',
    h.currentNav ? `${(((h.currentNav - h.avgNav) / h.avgNav) * 100).toFixed(2)}%` : 'N/A'
  ])
  
  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Code', 'Name', 'Units', 'Avg NAV', 'Invested', 'Current NAV', 'Current Value', 'Gain/Loss']],
    body: holdingsData,
    theme: 'striped',
    headStyles: { fillColor: [30, 58, 138] },
    styles: { fontSize: 8 },
    columnStyles: {
      1: { cellWidth: 50 }
    }
  })
  
  // Footer
  doc.setFontSize(8)
  doc.text('Generated by Mutual Fund Platform', 14, doc.internal.pageSize.height - 10)
  
  doc.save(fileName)
}

/**
 * Export portfolio data to Excel
 * @param {Object} portfolioSummary - Portfolio summary data
 * @param {Array} holdings - Array of holding objects
 * @param {string} fileName - Output file name
 */
export function exportPortfolioToExcel(portfolioSummary, holdings, fileName = 'portfolio-report.xlsx') {
  // Create workbook
  const wb = XLSX.utils.book_new()
  
  // Summary Sheet
  const summaryData = [
    ['Portfolio Summary Report'],
    ['Generated on', new Date().toLocaleDateString()],
    [],
    ['Metric', 'Value'],
    ['Total Invested', portfolioSummary.totalInvested],
    ['Current Value', portfolioSummary.currentValue],
    ['Total Return', portfolioSummary.totalReturn],
    ['Return %', portfolioSummary.returnPercentage],
    ['Number of Holdings', portfolioSummary.holdingsCount]
  ]
  
  const summaryWs = XLSX.utils.aoa_to_sheet(summaryData)
  XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary')
  
  // Holdings Sheet
  const holdingsHeaders = ['Code', 'Name', 'Units', 'Average NAV', 'Total Invested', 'Current NAV', 'Current Value', 'Unrealized Gain/Loss', 'Return %']
  const holdingsData = holdings.map(h => ({
    'Code': h.code,
    'Name': h.name,
    'Units': h.units,
    'Average NAV': h.avgNav,
    'Total Invested': h.units * h.avgNav,
    'Current NAV': h.currentNav || 'N/A',
    'Current Value': h.currentNav ? h.units * h.currentNav : 'N/A',
    'Unrealized Gain/Loss': h.currentNav ? (h.units * h.currentNav) - (h.units * h.avgNav) : 'N/A',
    'Return %': h.currentNav ? (((h.currentNav - h.avgNav) / h.avgNav) * 100) : 'N/A'
  }))
  
  const holdingsWs = XLSX.utils.json_to_sheet(holdingsData, { header: holdingsHeaders })
  XLSX.utils.book_append_sheet(wb, holdingsWs, 'Holdings')
  
  // Transactions Sheet
  const allTransactions = holdings.flatMap(h => 
    h.transactions.map(t => ({
      'Fund Code': h.code,
      'Fund Name': h.name,
      'Date': t.date,
      'Type': t.type,
      'Units': t.units,
      'NAV': t.nav,
      'Amount': t.units * t.nav
    }))
  )
  
  if (allTransactions.length > 0) {
    const transactionsWs = XLSX.utils.json_to_sheet(allTransactions)
    XLSX.utils.book_append_sheet(wb, transactionsWs, 'Transactions')
  }
  
  // Save file
  XLSX.writeFile(wb, fileName)
}

/**
 * Export fund comparison to PDF
 * @param {Array} funds - Array of fund comparison data
 * @param {string} fileName - Output file name
 */
export function exportComparisonToPDF(funds, fileName = 'fund-comparison.pdf') {
  const doc = new jsPDF()
  
  doc.setFontSize(20)
  doc.text('Mutual Fund Comparison Report', 14, 20)
  
  doc.setFontSize(10)
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30)
  
  const comparisonData = funds.map(f => [
    f.meta?.schemeCode || f.code,
    f.meta?.scheme_name || f.name,
    f.data?.[0]?.nav || 'N/A',
    f.data?.[0]?.date || 'N/A',
    f.returns?.m3 || 'N/A',
    f.returns?.m6 || 'N/A',
    f.returns?.y1 || 'N/A',
    f.returns?.y3 || 'N/A'
  ])
  
  doc.autoTable({
    startY: 40,
    head: [['Code', 'Name', 'Latest NAV', 'Date', '3M %', '6M %', '1Y %', '3Y %']],
    body: comparisonData,
    theme: 'striped',
    headStyles: { fillColor: [30, 58, 138] },
    styles: { fontSize: 9 },
    columnStyles: {
      1: { cellWidth: 60 }
    }
  })
  
  doc.setFontSize(8)
  doc.text('Generated by Mutual Fund Platform', 14, doc.internal.pageSize.height - 10)
  
  doc.save(fileName)
}

/**
 * Export goal progress to PDF
 * @param {Object} goal - Goal object
 * @param {Object} progress - Progress analysis
 * @param {string} fileName - Output file name
 */
export function exportGoalToPDF(goal, progress, fileName = 'goal-report.pdf') {
  const doc = new jsPDF()
  
  doc.setFontSize(20)
  doc.text('Goal Planning Report', 14, 20)
  
  doc.setFontSize(14)
  doc.text(goal.name, 14, 35)
  
  const goalData = [
    ['Target Amount', `₹${goal.targetAmount.toLocaleString('en-IN')}`],
    ['Target Date', new Date(goal.targetDate).toLocaleDateString()],
    ['Current Value', `₹${goal.currentValue.toLocaleString('en-IN')}`],
    ['Monthly SIP', `₹${goal.monthlySip.toLocaleString('en-IN')}`],
    ['Progress', `${progress.progressPercentage.toFixed(2)}%`],
    ['Projected Value', `₹${progress.projectedValue.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`],
    ['Gap', `₹${progress.gap.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`],
    ['Status', progress.onTrack ? 'On Track ✓' : 'Gap Identified ⚠'],
    ['Required SIP (if gap)', progress.requiredSip > 0 ? `₹${progress.requiredSip.toLocaleString('en-IN')}` : 'N/A']
  ]
  
  doc.autoTable({
    startY: 45,
    head: [['Parameter', 'Value']],
    body: goalData,
    theme: 'striped',
    headStyles: { fillColor: [30, 58, 138] }
  })
  
  doc.setFontSize(8)
  doc.text('Generated by Mutual Fund Platform', 14, doc.internal.pageSize.height - 10)
  
  doc.save(fileName)
}

/**
 * Generate and download capital gains report
 * @param {Array} holdings - Array of holdings with transactions
 * @param {string} fileName - Output file name
 */
export function exportCapitalGainsReport(holdings, fileName = 'capital-gains-report.xlsx') {
  const wb = XLSX.utils.book_new()
  
  // Calculate gains for each transaction
  const gainsData = holdings.flatMap(h => {
    return h.transactions
      .filter(t => t.type === 'sell')
      .map(t => {
        const buyPrice = h.avgNav // Simplified - should use FIFO matching
        const sellPrice = t.nav
        const units = t.units
        const gain = (sellPrice - buyPrice) * units
        const holdingPeriodDays = (new Date(t.date) - new Date(h.investedDate)) / (1000 * 60 * 60 * 24)
        const gainType = holdingPeriodDays > 365 ? 'Long Term' : 'Short Term'
        
        return {
          'Fund Code': h.code,
          'Fund Name': h.name,
          'Buy Date': h.investedDate,
          'Sell Date': t.date,
          'Units': units,
          'Buy NAV': buyPrice,
          'Sell NAV': sellPrice,
          'Sell Value': sellPrice * units,
          'Cost Basis': buyPrice * units,
          'Gain/Loss': gain,
          'Gain Type': gainType,
          'Holding Period (Days)': Math.floor(holdingPeriodDays)
        }
      })
  })
  
  if (gainsData.length > 0) {
    const ws = XLSX.utils.json_to_sheet(gainsData)
    XLSX.utils.book_append_sheet(wb, ws, 'Capital Gains')
    
    // Summary
    const shortTermGains = gainsData
      .filter(g => g['Gain Type'] === 'Short Term')
      .reduce((sum, g) => sum + g['Gain/Loss'], 0)
    const longTermGains = gainsData
      .filter(g => g['Gain Type'] === 'Long Term')
      .reduce((sum, g) => sum + g['Gain/Loss'], 0)
    
    const summaryData = [
      ['Capital Gains Summary'],
      [],
      ['Type', 'Total Gain/Loss'],
      ['Short Term', shortTermGains],
      ['Long Term', longTermGains],
      ['Total', shortTermGains + longTermGains]
    ]
    
    const summaryWs = XLSX.utils.aoa_to_sheet(summaryData)
    XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary')
  }
  
  XLSX.writeFile(wb, fileName)
}
